info:
  component: Turbine

PREFIX:
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

turbine:
  clusterNameExpression: new String("default")
  appConfig: pdf-creator-service

server:
  port: ${PORT:8989}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}

management:
  port: 8990

logging:
  level:
    root: INFO
    com.netflix.discovery: 'INFO'
    # org.springframework.integration: DEBUG

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10

---
spring:
  profiles: cloud
management:
  port: -1