info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: '*'
  routes:
    payrollservice: 
      path: /service-payroll/**

server:
  port: 8765

logging:
  level:
    ROOT: INFO